### ISSUE TITLE
Infinite error loop if user quit Spotify app

### ISSUE THREAD

**Issue by jan-bausch** [lrholmes/spotify-connect-ws#1]
If a user quits the Spotify app, polling of the API fails without error handling.
This is because the polling interval continuously tries to fetch `/me/player` but does not implement a catch-Function.

```
(node:1598) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://api.spotify.com/v1/me/player reason: Unexpected end of JSON input
    at /Users/<...>/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:1598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1598) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://api.spotify.com/v1/me/player reason: Unexpected end of JSON input
    at /Users/<...>/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
...
```

**Comment by lrholmes** [comment]
Thanks for the report and contribution @jfbausch!

Just to be sure, you mean that this error occurs when the user quits the playback app, right? 

I'm trying to think about the best way to handle that, and I'm not sure that we should be closing the connection, rather than reporting the failure as an error to the client (it may be useful to let the user know that something's gone wrong).

But you're right that we should absolutely be handling that promise rejection in some way. I'll do some testing later on and we'll get this issue sorted!

**Comment by jan-bausch** [comment]
> Just to be sure, you mean that this error occurs when the user quits the playback app, right?

Yeah, exactly - either by quitting the app, closing the browser tab or login out.

Thanks for the quick response. Hit me up, if I can help you with something.

**Comment by lrholmes** [comment]
Hey @jfbausch, thanks again for reporting this issue! I had a look into it and noticed a bunch of ways that the error logic could be improved. To fix the issue you directly mentioned, I have started to check the status code returned by Spotify in the 'getPlayerState' method. It seems to return a 202 when there is no active device (and no JSON, which caused the error), so we can do one better than sending a generic error, and instead detect the issue and let the client know what's gone wrong with a more descriptive message.

This change has been pushed to npm as v0.1.0, please let me know if this resolves the issue for you!

**Comment by jan-bausch** [comment]
Thank you very much for investing your time in this helpful library - works like a charm in my case.

**Comment by lrholmes** [comment]
Glad to hear it! Please feel free to report any more issues that you encounter, I'll be happy to help. And send a link over if/when you publish your project!
